### PR TITLE
GitHub action releases

### PR DESCRIPTION
**Pull request by dirkhh**
### Describe the pull request:

- [x] Build system change

### Pull request long description:

This updates our Windows build container to be the latest and greatest components / compilers available via MXE and then creates GitHub releases with the Windows artifacts and an Android apk for side-loading

### Changes made:

1) minor changes to the Windows build container creation script (and then, offline, creating / pushing said new container)
2) changes to the GitHub Actions for Windows and Android to push artifacts to GitHub releases
3) various small cleanups to try to be more consistent and make more sense with all this 

### Documentation change:

Once we have settled on how exactly we want to do this longer term, we need to document this for our users.

### Mentions:

@mikeller @bstoeger @atdotde

### CODE REVIEW

**Comment by dirkhh** [comment]
@neolit123 
Lubomir - we haven't had a Windows developer look at what we are doing in years... if you have a little spare time and wouldn't mind taking a look, that would be awesome. BLE continues to be... challenging.

**Review by neolit123 — COMMENTED** [review]
hello, the version bumps and other changes here make sense to me.
LGTM

**Comment by neolit123** [comment]
> BLE continues to be... challenging.

my information is out of date on what Subsurface is doing and whether Windows removed the pairing requirement [1] and fixed the connection flakyness [2].

this thread hints that they fixed [1]:
https://github.com/woodemi/quick_blue/issues/78#issuecomment-1078877700

>> On Windows 10 1703 and above you do not need to pair with your device manually. You can discover nearby Bluetooth LE device using in-app discovering.

[2] was random per different DCs, which was discouraging.

**Comment by dirkhh** [comment]
And with this I /think/ we have working Android apk's as well.

I will boldly merge this on my laptop in order to deal with the version number confusion that we'll get otherwise due to the magic builds that I have done here...

**Comment by mikeller** [comment]
Late to the party, but looks good to me.

@jefdriesen - I think this contains the version updates in the Windows build container that you were looking for to make BLE work for some dive computer models.

**Comment by jefdriesen** [comment]
I'll have a look as soon as I have some time.
@dirkhh Do you still have the build logs of the new docker container to check which BLE implementation (win32 or winrt) is enabled in the Qt build?

**Pull request merged**
